# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestPingppDashboard():

    def setup_method(self, method):
      self.driver = webdriver.Chrome()
      self.vars = {}

    def teardown_method(self, method):
      self.driver.quit()

    def test_pingppDashboard(self):
      self.driver.get("https://www.pingxx.com/")
      self.vars["root"] = self.driver.current_window_handle
      assert self.driver.title == "「简米｜Ping++」聚合支付系统-支付分账接口-B2B 支付解决方案-二清支付公司"
    
      WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.LINK_TEXT, "登录")))
      elements = self.driver.find_elements(By.LINK_TEXT, "登录")
      # 点击登录按钮
      assert len(elements) > 0
      # 点击进入账号填写页
      self.driver.find_element(By.XPATH, "//*[@id=\"index-top-bar\"]/div/div[2]/div/div[3]/ul/li[3]/a").click()
      self.driver.find_element(By.CSS_SELECTOR, ".li-login:nth-child(2)").click()
      self.driver.find_element(By.NAME, "username").send_keys("your_username")
      self.driver.find_element(By.ID, "password").click()
      self.driver.find_element(By.ID, "password").send_keys("your_password")
      self.driver.find_element(By.NAME, "action").click()
      self.driver.find_element(By.LINK_TEXT, "查看用量").click()
  
