# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service
from chromedriver_py import binary_path # this will get you the path variable
from selenium.webdriver.common.by import By

class TestWebsite():
  def setup_method(self, method):
    # service_object = Service(binary_path)
    # self.driver = webdriver.Chrome(service=service_object)

    # 下面语句执行成功的前提是，环境变量 chromedriver 版本要支持执行环境的 chrome 浏览器版本
    self.driver = webdriver.Chrome()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_website(self):
    self.driver.get("https://www.pingxx.com/")
    self.driver.set_window_size(1665, 1027)
    self.driver.find_element(By.LINK_TEXT, "产品").click()
    self.driver.find_element(By.LINK_TEXT, "解决方案").click()
  
